simple_oauth.oauth2_token.bundle.*:
  type: config_entity
  label: 'OAuth2 token type'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    locked:
      type: boolean
      label: 'Locked'

simple_oauth.settings:
  type: config_object
  label: 'Simple OAuth Settings'
  mapping:
    access_token_expiration:
      type: integer
      label: 'Access Token Expiration Time'
      description: 'The default period in seconds while a access token is valid'
    refresh_token_expiration:
      type: integer
      label: 'Refresh Token Expiration Time'
      description: 'The default period in seconds while a refresh token is valid'
    token_cron_batch_size:
      type: integer
      label: 'Token batch size'
      description: 'The number of expired token to delete per batch during cron cron'
    public_key:
      type: path
      label: 'Public Key'
      description: 'The path to the public file.'
    private_key:
      type: path
      label: 'Private Key'
      description: 'The path to the private file.'
    remember_clients:
      type: boolean
      label: 'Remember clients'
